development:
  password: $1
  theme_id: "$3"
  store: $2.myshopify.com
  ignore_files:
    - config.yml
    - Gruntfile.js
    - package.json
    - node_modules/
    - .git/
  production:
    password: $1
    theme_id: "$4"
    store: $2.myshopify.com
    timeout: 60s
    readonly: true